Fix undefined raise_unless_primary_instance_exists
Fix `NameError: undefined local variable or method
'raise_unless_primary_instance_exists'` when getting a list of
availabilities.

Even though the AvailabilitiesController only exists for the v0.1 API it
still needs to include the v0::IndexMixin which is where the
raise_unless_primary_instance_exists method is defined.